mall/views.py
from flask import Blueprint, render_template, url_for, request, abort, flash, redirect

from forms import ProductEditForm
from models import Product, db

mall = Blueprint('mall', __name__, template_folder='templates', static_folder='static')

@mall.route('/product/list/<int:page>')
# @login_required
def product_list(page):
    page_size = 5
    name = request.args.get('name', '')
    product = Product.query.filter(Product.name.contains(name), Product.is_valid==True)
    page_data = product.paginate(page=page, per_page=page_size)
    return render_template('product_list.html', page_data=page_data, page_size=page_size)


@mall.route('/product/detail/<uid>')
def product_detail(uid):
    prod_obj = Product.query.filter_by(uid=uid).first_or_404()
    return render_template('product_detail.html', prod_obj=prod_obj)


@mall.route('/product/edit/<uid>', methods=['GET', 'POST'])
def product_edit(uid):
    prod_obj = Product.query.filter_by(uid=uid, is_valid=True).first()
    if prod_obj is None:
        abort(404)
    form = ProductEditForm(obj=prod_obj)
    if form.validate_on_submit():
        prod_obj.name = form.name.data
        prod_obj.content = form.content.data
        prod_obj.desc = form.desc.data
        prod_obj.types = form.types.data
        prod_obj.price = form.price.data
        prod_obj.origin_price = form.origin_price.data
        prod_obj.img = 'xxx.jpg'
        prod_obj.channel = form.channel.data
        prod_obj.buy_link = form.buy_link.data
        prod_obj.status = form.status.data
        prod_obj.sku_count = form.sku_count.data
        prod_obj.remain_count = form.remain_count.data
        prod_obj.view_count = form.view_count.data
        prod_obj.score = form.score.data
        prod_obj.is_valid = form.is_valid.data
        prod_obj.reorder = form.reorder.data
        db.session.add(prod_obj)
        db.session.commit()
        flash('修改商品成功', 'success')
        return redirect(url_for('mall.product_list', page=1))
    else:
        print(form.errors)
        flash('请修改页面中的页面错误', 'warning')
    return render_template('product_edit.html', form=form, uid=uid)


@mall.route('/product/add', methods=['GET', 'POST'])
def product_add():
    form = ProductEditForm()
    if form.validate_on_submit():
        prod_obj = Product(
            name=form.name.data,
            content=form.content.data,
            desc=form.desc.data,
            types=form.types.data,
            price=form.price.data,
            origin_price=form.origin_price.data,
            img='xxx.jpg',
            channel=form.channel.data,
            buy_link=form.buy_link.data,
            status=form.status.data,
            sku_count=form.sku_count.data,
            remain_count=form.remain_count.data,
            view_count=form.view_count.data,
            score=form.score.data,
            is_valid=form.is_valid.data,
            reorder=form.reorder.data,
        )
        db.session.add(prod_obj)
        db.session.commit()
        flash('新增商品成功', 'success')
        return redirect(url_for('mall.product_list', page=1))
    else:
        print(form.errors)
        flash('请修改页面中的页面错误', 'warning')
    return render_template('product_add.html', form=form)


@mall.route('/product/delete/<uid>', methods=['GET', 'POST'])
def product_delete(uid):
    prod_obj = Product.query.filter_by(uid=uid, is_valid=True).first()
    if prod_obj is None:
        return 'no'
    prod_obj.is_valid = False
    db.session.add(prod_obj)
    db.session.commit()
    return 'ok'

mall/templates/product_add.html
{% extends 'base/base.html' %}
{% block title %}
<title>新增商品</title>
{% endblock %}

{% block content %}
    <h1>新增商品</h1>
    <form action="{{ url_for('mall.product_add') }}" method="post" enctype="multipart/form-data">
      <div class="form-group">
        {#   商品名称  #}
          {{ form.name.label }}
          {{ form.name }}
          <p class="help-block">{{ form.name.description }}</p>
      </div>
      <div class="form-group">
           {#   商品描述  #}
        {{ form.content.label }}{{ form.content }}
      </div>
        <div class="form-group">
        {{ form.desc.label }}{{ form.desc }}
      </div>
        <div class="form-group">
           {#   类型  #}
        {{ form.types.label }}{{ form.types }}
      </div>
        <div class="form-group">
           {#   销售价格  #}
        {{ form.price.label }}{{ form.price }}
      </div>
        <div class="form-group">
           {#   商品原价  #}
        {{ form.origin_price.label }}{{ form.origin_price }}
      </div>
        <div class="form-group">
           {#   商品主图  #}
        {{ form.img.label }}{{ form.img }}
      </div>
        <div class="form-group">
           {#   渠道  #}
        {{ form.channel.label }}{{ form.channel }}
      </div>
      <div class="form-group">
           {#   链接  #}
        {{ form.buy_link.label }}{{ form.buy_link }}
      </div>
      <div class="form-group">
           {#   商品状态  #}
        {{ form.status.label }}{{ form.status }}
      </div>
      <div class="form-group">
           {#   库存  #}
        {{ form.sku_count.label }}{{ form.sku_count }}
      </div>
      <div class="form-group">
           {#   剩余库存  #}
        {{ form.remain_count.label }}{{ form.remain_count }}
      </div>
      <div class="form-group">
           {#   浏览次数  #}
        {{ form.view_count.label }}{{ form.view_count }}
      </div>
        <div class="form-group">
           {#   评分  #}
        {{ form.score.label }}{{ form.score }}
      </div>
        <div class="checkbox">
        <label>
          {{ form.is_valid }}{{ form.is_valid.label.text }}
        </label>
      </div>
        <div class="form-group">
           {#   排序  #}
        {{ form.reorder.label }}{{ form.reorder }}
      </div>

      <button type="submit" class="btn btn-default">Submit</button>


        {{ form.csrf_token }}
    </form>
{% endblock %}

mall/templates/product_detail.html
{% extends 'base/base.html' %}
{% block title %}
<title>{{ prod_obj.name }}</title>
{% endblock %}

{% block content %}
    <h2>{{ prod_obj.name }}</h2>
    <p>{{ prod_obj.desc }}</p>
{% endblock %}

mall/templates/product_edit.html
{% extends 'base/base.html' %}
{% block title %}
<title>新增商品</title>
{% endblock %}

{% block content %}
    <h1>新增商品</h1>
    <form action="{{ url_for('mall.product_edit', uid = uid) }}" method="post" enctype="multipart/form-data">
      <div class="form-group">
        {#   商品名称  #}
          {{ form.name.label }}
          {{ form.name }}
          <p class="help-block">{{ form.name.description }}</p>
      </div>
      <div class="form-group">
           {#   商品描述  #}
        {{ form.content.label }}{{ form.content }}
      </div>
        <div class="form-group">
        {{ form.desc.label }}{{ form.desc }}
      </div>
        <div class="form-group">
           {#   类型  #}
        {{ form.types.label }}{{ form.types }}
      </div>
        <div class="form-group">
           {#   销售价格  #}
        {{ form.price.label }}{{ form.price }}
      </div>
        <div class="form-group">
           {#   商品原价  #}
        {{ form.origin_price.label }}{{ form.origin_price }}
      </div>
        <div class="form-group">
           {#   商品主图  #}
        {{ form.img.label }}{{ form.img }}
      </div>
        <div class="form-group">
           {#   渠道  #}
        {{ form.channel.label }}{{ form.channel }}
      </div>
      <div class="form-group">
           {#   链接  #}
        {{ form.buy_link.label }}{{ form.buy_link }}
      </div>
      <div class="form-group">
           {#   商品状态  #}
        {{ form.status.label }}{{ form.status }}
      </div>
      <div class="form-group">
           {#   库存  #}
        {{ form.sku_count.label }}{{ form.sku_count }}
      </div>
      <div class="form-group">
           {#   剩余库存  #}
        {{ form.remain_count.label }}{{ form.remain_count }}
      </div>
      <div class="form-group">
           {#   浏览次数  #}
        {{ form.view_count.label }}{{ form.view_count }}
      </div>
        <div class="form-group">
           {#   评分  #}
        {{ form.score.label }}{{ form.score }}
      </div>
        <div class="checkbox">
        <label>
          {{ form.is_valid }}{{ form.is_valid.label.text }}
        </label>
      </div>
        <div class="form-group">
           {#   排序  #}
        {{ form.reorder.label }}{{ form.reorder }}
      </div>

      <button type="submit" class="btn btn-default">Submit</button>


        {{ form.csrf_token }}
    </form>
{% endblock %}

mall/templates/product_list.html
{% extends 'base/base.html' %}
{% block title %}
    <title>商品管理</title>
{% endblock %}
{% block content %}
  <h2 class="sub-header">商品列表</h2>
  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>#</th>
          <th>名称</th>
          <th>价格</th>
          <th>状态</th>
          <th>操作</th>
        </tr>
      </thead>
      <tbody>
       {% for product in page_data.items %}
        <tr>
          <td>{{ product.id }}</td>
          <td>{{ product.name }}</td>
          <td>{{ product.price }}</td>
          <td>{{ product.status }}</td>
          <td>
              <a href="{{ url_for('mall.product_detail', uid=product.uid) }}" class="btn btn-default">详情</a>
              <a href="{{ url_for('mall.product_edit', uid=product.uid) }}" class="btn btn-default" >编辑</a>
              <a href="" class="btn btn-default del-prod" data-url="{{ url_for('mall.product_delete', uid=product.uid) }}">删除</a>
          </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
  <nav aria-label="Page navigation" class="pull-right">
        总共{{ page_data.total }}条记录，总共{{ page_data.pages }}页
        {% set name = request.args.get('name', '') %}
        <ul class="pagination">
            <li>
                {% if page_data.has_prev %}
                        <a href="{{ url_for('mall.product_list', page=page_data.prev_num) }}?name={{ name }}" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    {% else %}
                        <a class="disabled" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                {% endif %}
            </li>
            {% for page_num in page_data.iter_pages() %}
                {% if page_num %}
                    <li><a href="{{ url_for('mall.product_list', page=page_num) }}?name={{ name }}">{{ page_num }}</a></li>
                {% else %}
                    <li><a>....</a></li>
                {% endif %}
            {% endfor %}
            <li>
                {% if page_data.has_next %}
                    <a href="{{ url_for('mall.product_list', page=page_data.next_num) }}?name={{ name }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                {% else %}
                    <a class="disabled" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                {% endif %}
            </li>
        </ul>
  </nav>
{% endblock %}
{% block extrajs %}
    <script type="text/javascript">
        $('.del-prod').click(function () {
            var url = $(this).attr('data-url')
            if(window.confirm('确认删除该商品吗')){
                $.post(url,function (rest) {
                    if(rest == 'ok'){
                        alert('删除成功')
                    }else {
                        alert('删除失败')
                    }
                })
            }
        })
    </script>
{% endblock %}