accounts/views.py
from flask import Blueprint, render_template, url_for, flash, session, redirect, g

from forms import LoginForm
from models import User

accounts = Blueprint('accounts', __name__, template_folder='templates', static_folder='static')


@accounts.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        user = User.query.filter_by(username=username, password=password).first()
        if user is None:
            flash('用户名密码错误', 'danger')
        else:
            session['user_id'] = user.id
            flash('欢迎回来', 'success')
            return redirect(url_for('index'))
    return render_template('login.html', form=form)

@accounts.route('/logout')
def logout():
    session['user_id'] = None
    g.user = None
    flash('欢迎下次再来', 'success')
    return redirect(url_for('accounts.login'))

mall/views.py
from flask import Blueprint, render_template, url_for, request, abort, flash, redirect

from forms import ProductEditForm
from models import Product, db

mall = Blueprint('mall', __name__, template_folder='templates', static_folder='static')

@mall.route('/product/list/<int:page>')
# @login_required
def product_list(page):
    page_size = 5
    name = request.args.get('name', '')
    product = Product.query.filter(Product.name.contains(name), Product.is_valid==True)
    page_data = product.paginate(page=page, per_page=page_size)
    return render_template('product_list.html', page_data=page_data, page_size=page_size)


@mall.route('/product/detail/<uid>')
def product_detail(uid):
    prod_obj = Product.query.filter_by(uid=uid).first_or_404()
    return render_template('product_detail.html', prod_obj=prod_obj)


@mall.route('/product/edit/<uid>', methods=['GET', 'POST'])
def product_edit(uid):
    prod_obj = Product.query.filter_by(uid=uid, is_valid=True).first()
    if prod_obj is None:
        abort(404)
    form = ProductEditForm(obj=prod_obj)
    if form.validate_on_submit():
        prod_obj.name = form.name.data
        prod_obj.content = form.content.data
        prod_obj.desc = form.desc.data
        prod_obj.types = form.types.data
        prod_obj.price = form.price.data
        prod_obj.origin_price = form.origin_price.data
        prod_obj.img = 'xxx.jpg'
        prod_obj.channel = form.channel.data
        prod_obj.buy_link = form.buy_link.data
        prod_obj.status = form.status.data
        prod_obj.sku_count = form.sku_count.data
        prod_obj.remain_count = form.remain_count.data
        prod_obj.view_count = form.view_count.data
        prod_obj.score = form.score.data
        prod_obj.is_valid = form.is_valid.data
        prod_obj.reorder = form.reorder.data
        db.session.add(prod_obj)
        db.session.commit()
        flash('修改商品成功', 'success')
        return redirect(url_for('mall.product_list', page=1))
    else:
        print(form.errors)
        flash('请修改页面中的页面错误', 'warning')
    return render_template('product_edit.html', form=form, uid=uid)


@mall.route('/product/add', methods=['GET', 'POST'])
def product_add():
    form = ProductEditForm()
    if form.validate_on_submit():
        prod_obj = Product(
            name=form.name.data,
            content=form.content.data,
            desc=form.desc.data,
            types=form.types.data,
            price=form.price.data,
            origin_price=form.origin_price.data,
            img='xxx.jpg',
            channel=form.channel.data,
            buy_link=form.buy_link.data,
            status=form.status.data,
            sku_count=form.sku_count.data,
            remain_count=form.remain_count.data,
            view_count=form.view_count.data,
            score=form.score.data,
            is_valid=form.is_valid.data,
            reorder=form.reorder.data,
        )
        db.session.add(prod_obj)
        db.session.commit()
        flash('新增商品成功', 'success')
        return redirect(url_for('mall.product_list', page=1))
    else:
        print(form.errors)
        flash('请修改页面中的页面错误', 'warning')
    return render_template('product_add.html', form=form)


@mall.route('/product/delete/<uid>', methods=['GET', 'POST'])
def product_delete(uid):
    prod_obj = Product.query.filter_by(uid=uid, is_valid=True).first()
    if prod_obj is None:
        return 'no'
    prod_obj.is_valid = False
    db.session.add(prod_obj)
    db.session.commit()
    return 'ok'

templates/base/base.html
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    {% block title %}
    <title>商品管理</title>
    {% endblock %}
    <!-- Bootstrap -->
    <link href="{{ url_for('static', filename='bootstrap/css/bootstrap.min.css', _external=True) }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/style.css', _external=True) }}" rel="stylesheet">

    {% block extracss %}
        {# 其它页面的css #}
    {% endblock %}
    <!-- HTML5 shim 和 Respond.js 是为了让 IE8 支持 HTML5 元素和媒体查询（media queries）功能 -->
    <!-- 警告：通过 file:// 协议（就是直接将 html 页面拖拽到浏览器中）访问页面时 Respond.js 不起作用 -->
    <!--[if lt IE 9]>
      <script src="https://cdn.jsdelivr.net/npm/html5shiv@3.7.3/dist/html5shiv.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/respond.js@1.4.2/dest/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    {% block top %}
        {% include 'base/top.html' %}
    {% endblock %}
    <div class="container-fluid">
      {% for cat, msg in get_flashed_messages(with_categories=True) %}
        <div class="alert alert-{{ cat }}" role="alert">{{ msg }}</div>
      {% endfor %}
      {% block container %}
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          {% block sidebar %}
             {# 左侧菜单 #}
            {% include 'base/sidebar.html' %}
          {% endblock %}
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          {% block content %}

          {% endblock %}
        </div>
      </div> <!-- //end div.row -->
      {% endblock %}
    </div>


    <!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
    <script src="{{ url_for('static', filename='jquery/jquery.min.js', _external=True) }}"></script>
    <!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
    <script src="{{ url_for('static', filename='bootstrap/js/bootstrap.min.js', _external=True) }}"></script>
    {% block extrajs %}
        {# 其它页面的js #}
    {% endblock %}
  </body>
</html>

templates/base/sidebar.html
<ul class="nav nav-sidebar">
    <li class="active">
        <a href="{{ url_for('mall.product_list', page=1) }}">商品管理 <span class="sr-only">(current)</span>
        </a>
    </li>
    <li><a href="#">标签管理</a></li>
    <li><a href="{{ url_for('mall.product_add') }}">新增商品</a></li>
    <li><a href="#">分类管理</a></li>
  </ul>
  <ul class="nav nav-sidebar">
    <li><a href="">用户管理</a></li>
    <li><a href="">地址管理</a></li>
  </ul>
  <ul class="nav nav-sidebar">
    <li><a href="">订单管理</a></li>
  </ul>

templates/base/top.html
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">积分商城后台管理</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                {% if g.user %}
                    <li><a href="#">欢迎{{ g.user.nickname }}</a></li>
                {% endif %}
                    <li><a href="{{ url_for('accounts.logout') }}">退出登录</a></li>
    {#              <li><a href="#">Profile</a></li>#}
    {#              <li><a href="#">Help</a></li>#}
            </ul>
            <form class="navbar-form navbar-right" action="{{ url_for('mall.product_list',page=1) }}" method="get">
                <input type="text" class="form-control" placeholder="Search..." name="name">
                <input type="submit" class="form-control btn-primary" value="搜索">
            </form>
        </div>
    </div>
</nav>